#!/bin/bash

export PLUGIN_DIR="$CONFIG_DIR/plugins"
export ITEM_DIR="$CONFIG_DIR/items"

source "$CONFIG_DIR/colors.sh"

source "$CONFIG_DIR/bar.sh"
source "$CONFIG_DIR/defaults.sh"

source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"
source "$ITEM_DIR/aerospace_mode_indicator.sh"
source "$ITEM_DIR/left_background.sh"

source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/cpu.sh"
source "$ITEM_DIR/network.sh"
source "$ITEM_DIR/right_background.sh"

# Add spacer before music items
# sketchybar --add item music_spacer right \
#            --set music_spacer width=10 \
#                              background.color=0x00000000 \
#                              drawing=on
# 
# source "$ITEM_DIR/music.sh"
# source "$ITEM_DIR/music_background.sh"

sketchybar --update

